apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "telemetry-alertmanager"
spec:
  ports:
    - port: 9093
      targetPort: web
  selector:
    app: alertmanager
