#global: null
#receivers:
#- name: 'opsgenie-testing'
#  opsgenie_configs:
#  - api_key: 'ALERTMANAGER_OPSGENIE_TESTING_KEY'
#    #responders:
#    #- name: SolutionFactory
#    #  type: team
#- name: 'opsgenie-active'
#  opsgenie_configs:
#  - api_key: 'ALERTMANAGER_OPSGENIE_ACTIVE_KEY'
#    #responders:
#    #- name: "Mvision EDR"
#    #  type: team
#route:
#  group_by:
#    - job
#    - alertname
#    - service
#    - env
#  group_interval: 5m
#  group_wait: 10s
#  receiver: 'opsgenie-testing'
#  repeat_interval: 3h
#  routes:
#    - match:
#        stage: local
#      receiver: 'opsgenie-testing'
#      group_interval: 5m
#      group_wait: 10s
#      repeat_interval: 3h
#      continue: false
#    - match:
#        stage: testing
#      receiver: opsgenie-testing
#      group_interval: 5m
#      group_wait: 10s
#      repeat_interval: 3h
#      continue: false
#    - match:
#        stage: active
#      receiver: opsgenie-active
#      group_interval: 5m
#      group_wait: 10s
#      repeat_interval: 3h
#      continue: false
global: null
receivers:
- name: default-receiver
route:
  group_interval: 5m
  group_wait: 10s
  receiver: default-receiver
  repeat_interval: 3h
