apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: telemetry-pushgateway-pdb
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - telemetry-pushgateway

