apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database-compact
    app.kubernetes.io/instance: thanos-compact
    app.kubernetes.io/name: thanos-compact
  name: thanos-compact
spec:
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app.kubernetes.io/component: database-compact
    app.kubernetes.io/instance: thanos-compact
    app.kubernetes.io/name: thanos-compact
