apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-healthcheck-cm
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  health-check.conf: |
    [global]
    build = 0.0.1839
    [grafana]
    url = http://grafana-telemetry.monitoring.svc.cluster.local:3000
    type = http
    expected_http_status_code = 200
    expected_content = .*
    build = 0.0.1839

    [prometheus]
    url = http://prometheuslb.monitoring.svc.cluster.local:9090/-/healthy
    type = http
    expected_http_status_code = 200
    expected_content = .*
    build = 0.0.1839

    [pushgateway]
    url = http://pushgatewaylb.monitoring.svc.cluster.local:9091/-/healthy
    type = http
    expected_http_status_code = 200
    expected_content = .*
    build = 0.0.1839

    [alertmanager]
    url = http://alertmanager-service.monitoring.svc.cluster.local:9093/-/healthy
    type = http
    expected_http_status_code = 200
    expected_content = .*
    build = 0.0.1839

    [thanos-query-frontend]
    url = http://thanos-query-frontend-service.monitoring.svc.cluster.local:9090/-/healthy
    type = http
    expected_http_status_code = 200
    expected_content = .*
    build = 0.0.1839
