apiVersion: v1
kind: Secret
metadata:
  name: grafhelm-grafcharm
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    release: grafhelm
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4="
  ldap-toml: ""

