apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-elasticsearch
  labels:
     grafana_datasource: "1"
data:
  elasticsearch.yaml: |-
    apiVersion: 1
    datasources:
    - name: elasticsearch-logs
      type: elasticsearch
      access: proxy
      url: http://esearch-logs.logging.svc.cluster.local:9200 #TODO
      password: ''
      user: ''
      database: '[logstash-]YYYY.MM.DD'
      basicAuth: false
      basicAuthUser: ''
      basicAuthPassword: ''
      withCredentials: false
      isDefault: false
      jsonData:
        esVersion: 5
        interval: Daily
        timeField: '@timestamp'
      readOnly: false
      editable: true
    - name: elasticsearch-filebeat-logs
      type: elasticsearch
      access: proxy
      url: http://esearch-logs.logging.svc.cluster.local:9200 #TODO
      password: ''
      user: ''
      database: '[filebeat-*-]YYYY.MM.DD[-monitoring]'
      basicAuth: false
      basicAuthUser: ''
      basicAuthPassword: ''
      withCredentials: false
      isDefault: false
      jsonData:
        esVersion: 60
        interval: Daily
        timeField: '@timestamp'
      readOnly: false
      editable: true

