apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-cloudwatch
  labels:
     grafana_datasource: "1"
data:
  cloudwatch.yaml: |-
    apiVersion: 1
    datasources:
    - name: AWS-CloudWatch
      type: cloudwatch
      jsonData:
        authType: credentials
        defaultRegion: us-west-2
