apiVersion: v1
kind: Service
metadata:
  name: grafana-internal
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    release: grafhelm
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafcharm
    release: grafhelm
