apiVersion: v1
kind: Pod
metadata:
  name: postsync-pod
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
    - command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
      image: busybox
      imagePullPolicy: IfNotPresent
      name: postsync-sleep-pod
      volumeMounts:
      - name: postdeploycm-volume
        mountPath: /scripts
  volumes:
    - name: postdeploycm-volume
      configMap:
        name: deployscriptscm
        defaultMode: 0744
  dnsPolicy: ClusterFirst
  restartPolicy: Never
