apiVersion: v1
kind: Pod
metadata:
  name: presync-pod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
    - command: ['sh', '-c', 'echo Container 1 is Running ; sleep 10']
      image: busybox
      imagePullPolicy: IfNotPresent
      name: presync-sleep-pod
  dnsPolicy: ClusterFirst
  restartPolicy: Never
