apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    release: grafhelm
    heritage: Tiller
  name: grafana-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-crb
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    release: grafhelm
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: grafana-sa #TODO
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: grafana-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-role
  namespace: monitoring
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    heritage: Tiller
    release: grafhelm
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [""]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rb
  namespace: monitoring
  labels:
    app: grafcharm
    chart: grafcharm-4.0.4
    heritage: Tiller
    release: grafhelm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-rb
subjects:
- kind: ServiceAccount
  name: grafana-sa #TODO
  namespace: monitoring


---
