apiVersion: v1
kind: Service
metadata:
  name: grafana-telemetry
  labels:
    k8s-app: telemetry
    kubernetes.io/cluster-service: "true"
    app: grafana
    release: telemetry
    chart: grafana-3.8.19
    heritage: Tiller
spec:
  selector:
    app: "grafcharm"
    release: grafhelm
  ports:
  - port: 3000
    targetPort: 3000
  sessionAffinity: ClientIP
