apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
  - pdp.yaml
  - service.yaml
  - netpol/prometheus-network-policy.yml
  - rbac.yaml
secretGenerator:
- name: telemetry-additional-scrape-configs
  files:
  - secret/prometheus-additional.yaml
  options:
    disableNameSuffixHash: true

