## Service account for prometheus, not the operator but actual prometheus instances
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-telemetry
  annotations:
    eks.amazonaws.com/role-arn: __prometheus_rbac_arn

---
## This section is taken from the official prometheus operator repo
## The purpose is adding services accounts and default scrapping configurations
## https://github.com/coreos/prometheus-operator/tree/master/example/additional-scrape-configs

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-telemetry
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-telemetry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-telemetry
subjects:
- kind: ServiceAccount
  name: prometheus-telemetry
