apiVersion: v1
kind: Service
metadata:
  name: prometheuslb
  labels:
    k8s-app: prometheus
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    prometheus: telemetry
  ports:
  - port: __prometheus_port
    targetPort: 9090
