{
 "title": "AWS EC2 cost",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "solution",
    "label": "Solution",
    "query": "label_values(kube_pod_labels, label_solution)"
   },
   {
    "name": "aws_service",
    "label": "AWS service",
    "query": "label_values(aws_service_cost, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "EC2:Compute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(aws_project_cost{service=\"Amazon Elastic Compute Cloud - Compute\"})",
     "legendFormat": "Amazon Elastic Compute Cloud - Compute"
    }
   ]
  },
  {
   "title": "EBS:Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(aws_project_cost{service=\"EC2 - Other\", usage=~\".*EBS:VolumeUsage.*\"})",
     "legendFormat": "EBS:Volume"
    }
   ]
  },
  {
   "title": "EC2:Compute by solution ",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(edr_solution_compute_cost{label_solution!=\"\"}) by (label_solution)",
     "legendFormat": "{{label_solution}}"
    }
   ]
  },
  {
   "title": "EBS:Volume by solution",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "sum(edr_solution_persistentvolumeclaim_cost{label_solution!=\"\"}) by (label_solution)",
     "legendFormat": "{{label_solution}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<p><span style=\"text-decoration: underline;\">Note</span>: Data sent by AWS Cost Explorer corresponds to the previous time period (e.g., today's values ​​are yesterday's costs).</p>"
   }
  },
  {
   "title": "Other Amazon services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
     "repeat": "aws_service",
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 63 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    },
    {
     "title": "$aws_service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(aws_project_cost{service=\"$aws_service\"}) by (usage)",
       "legendFormat": "{{usage}}"
      }
     ]
    }
   ]
  }
 ]
}