{
 "title": "Service usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "solution",
    "label": "Solution",
    "query": "label_values(kube_pod_labels, label_solution)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(kube_pod_labels{label_solution=\"$solution\"}, label_service)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_status_running == 1) by (pod) *\n  sum(kube_pod_container_resource_requests_cpu_cores) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_status_running == 1) by (pod) *\n  sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) /\n  sum(kube_pod_container_resource_requests_cpu_cores) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Memory requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_status_running == 1) by (pod) *\n  sum(kube_pod_container_resource_requests_memory_bytes) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_status_running == 1) by (pod) *\n  sum(container_memory_working_set_bytes) by (pod) /\n  sum(kube_pod_container_resource_requests_memory_bytes) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Volume requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(\n    sum(kube_persistentvolumeclaim_status_phase == 1) by (persistentvolumeclaim) *\n    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim) * on(persistentvolumeclaim) group_right\n    sum(kube_pod_spec_volumes_persistentvolumeclaims_info) by (persistentvolumeclaim, pod)\n  ) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Volume usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(\n    sum(kube_persistentvolumeclaim_status_phase == 1) by (persistentvolumeclaim) *\n    sum(kubelet_volume_stats_used_bytes) by (persistentvolumeclaim) /\n    sum(kube_persistentvolumeclaim_resource_requests_storage_bytes) by (persistentvolumeclaim) * on(persistentvolumeclaim) group_right\n    sum(kube_pod_spec_volumes_persistentvolumeclaims_info) by (persistentvolumeclaim, pod)\n  ) by (pod) * on(pod) group_right\n  sum(kube_pod_labels{label_solution=\"$solution\", label_service=\"$service\"}) by (pod, label_app)\n) by (label_app)",
     "legendFormat": "{{label_app}}"
    }
   ]
  }
 ]
}